package com.winfo.project2.client;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SettingsUI extends VerticalLayout {
    protected CssLayout sideLayout;
    protected Label parsePortLabel;
    protected Button menuButton;
    protected CssLayout navigationlayout;
    protected Button homepageButton;
    protected Button uploaDataButton;
    protected HorizontalLayout headerLayout;
    protected Button aboutbutton;
    protected Button uploadsButton;
    protected Button settingsButton;
    protected VerticalLayout mainContentLayout;
    protected Label iPLabel;
    protected TextField iPTextfield;
    protected Label portLabel;
    protected TextField portTextfield;
    protected Button safeButton;
    protected Label safeLabel;
    protected HorizontalLayout footerlayout;
    protected Button contactButton;
    protected Button impressumButton;

    public SettingsUI() {
        Design.read(this);
    }
}
