package com.winfo.project2.client.basic.GUI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UploadUI extends HorizontalLayout {
    protected CssLayout sideLayout;
    protected Image parsePortLogo;
    protected Button menuButton;
    protected CssLayout navigationlayout;
    protected Button homepageButton;
    protected Button uploadButton;
    protected HorizontalLayout headerLayout;
    protected Button aboutbutton;
    protected Button uploadsButton;
    protected Button settingsButton;
    protected VerticalLayout mainContent;
    protected Label fileTypeLabel;
    protected ComboBox fileTypeBox;
    protected Label filePathLabel;
    protected TextField pathField;
    protected Button importButton;
    protected Panel previewPanel;
    protected HorizontalLayout footerlayout;
    protected Button contactButton;

    public UploadUI() {
        Design.read(this);
    }
}
