package com.winfo.project2.client.basic.GUI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * Created by patrick on 13.06.17.
 */
public class UploadUI extends MainUI {
    public static final String VIEW_NAME = "upload";

    public UploadUI() {

    }

    public VerticalLayout getLayout () {

        Label headerLabel = new Label();
        headerLabel.setStyleName("h1");
        VerticalLayout vertical = new VerticalLayout ();

        headerLabel.setValue("Upload");

        //input form
        FormLayout form = new FormLayout();

        TextField fileType = new TextField("File Type");

        fileType.setRequiredIndicatorVisible(true);
        fileType.setIcon(FontAwesome.SITEMAP);

        TextField path = new TextField("Path");
        path.setIcon(FontAwesome.EXTERNAL_LINK);
        path.setRequiredIndicatorVisible(true);


        form.addComponents(fileType, path);

        Button button = new Button("Save me");
        form.addComponent(button);
        //Button click
        button.addClickListener( e -> {
            //create new entity object
            ///////////////////////////////////Entity en = new Entity(datasource.getValue(), backlink.getValue(), classification.getValue(), Integer.valueOf(loadedAt.getValue()), completeText.getValue());

            //create json out of new object
            ///////////////////////////////////String newEntityJson = gson.toJson(en);
            //post json through serverconnector
            ///////////////////////////////////server.postJSON("/entities", newEntityJson);

            //refresh page (remove if possible!!) > refresh grid like above at the delete method > problem: form is still filled with data!
            ////////////////////////////////////////Page.getCurrent().reload();
            vertical.addComponent(new Label("(not really) saved"));
        });


        vertical.addComponents(headerLabel, form);

//        mainContent.removeAllComponents();
//        mainContent.addComponents(vertical);
        return vertical;
    }
}
