package com.winfo.project2.client.basic.GUI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UploadedUI extends HorizontalLayout {
    protected CssLayout sideLayout;
    protected Image parsePortLogo;
    protected Button menuButton;
    protected CssLayout navigationlayout;
    protected Button homepageButton;
    protected Button uploadButton;
    protected HorizontalLayout headerLayout;
    protected Button aboutbutton;
    protected Button uploadsButton;
    protected Button settingsButton;
    protected HorizontalLayout mainContent;
    protected Grid dataGrid;
    protected HorizontalLayout footerlayout;
    protected Button contactButton;

    public UploadedUI() {
        Design.read(this);
    }
}
